In [18]:
## ANURAN_7

##### AZRI ZAMRUD BIN KIMIN (153507)
##### HAZIQ BIN HIZUL (152270)
##### MUHAMMAD ARMAND BIN MUHAMAD FAZLI (153857)
##### SYED MUHAMMAD HAIKAL BIN SYED HUSNI (153086)

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib notebook

In [2]:
dataset = pd.read_csv('frogs_mfcc.csv')

In [3]:

#Declaring feature vector and target variable
#note: Saya assume variable yang kita nak target tu species sebab itu je yang berlainan

X = dataset.iloc[:,0:22]

In [4]:
X=pd.get_dummies(X)

In [5]:
X=X.values

In [6]:
X

array([[ 1.00000000e+00,  1.52936298e-01, -1.05585903e-01, ...,
         5.76839754e-02,  1.18680135e-01,  1.40384457e-02],
       [ 1.00000000e+00,  1.71534257e-01, -9.89747371e-02, ...,
         2.01399631e-02,  8.22629869e-02,  2.90557422e-02],
       [ 1.00000000e+00,  1.52317085e-01, -8.29726739e-02, ...,
        -2.50832268e-02,  9.91083997e-02,  7.71623847e-02],
       ...,
       [ 1.00000000e+00, -5.82556781e-01, -3.43237394e-01, ...,
         2.78338002e-02, -5.30614770e-04, -8.04253341e-02],
       [ 1.00000000e+00, -5.19497158e-01, -3.07553060e-01, ...,
         4.18033791e-02, -2.79113834e-02, -9.68953698e-02],
       [ 1.00000000e+00, -5.08833178e-01, -3.24105837e-01, ...,
         3.15595726e-02, -2.93554758e-02, -8.79096248e-02]])

In [7]:
y=dataset.iloc[:,-1].values

In [8]:

#Split data into separate training and test set
#note: untuk machine learning dia perlu ada training set dengan test set
#note: nombor test_size dengan random_state tu sya tengok memang recommended kat google

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [10]:
KNN = KNeighborsClassifier(n_neighbors=5,
weights = 'uniform',
algorithm = 'kd_tree',
leaf_size =30,
p=2,
metric='minkowski',
metric_params=None,
n_jobs=-1)

In [11]:
KNN.fit(X_train, y_train)

KNeighborsClassifier(algorithm='kd_tree', n_jobs=-1)

In [12]:
y_pred = KNN.predict(X_test)

In [13]:
from sklearn.metrics import classification_report, confusion_matrix

In [16]:
print(classification_report(y_test, y_pred))

                        precision    recall  f1-score   support

        AdenomeraAndre       0.96      0.97      0.97       146
AdenomeraHylaedactylus       1.00      1.00      1.00       694
    Ameeregatrivittata       0.99      0.99      0.99       106
            HylaMinuta       0.96      0.91      0.94        57
  HypsiboasCinerascens       0.94      0.99      0.96        90
     HypsiboasCordobae       0.99      0.99      0.99       231
   LeptodactylusFuscus       0.96      1.00      0.98        54
 OsteocephalusOophagus       1.00      0.70      0.82        20
     Rhinellagranulosa       1.00      0.88      0.94        17
           ScinaxRuber       1.00      0.96      0.98        24

              accuracy                           0.98      1439
             macro avg       0.98      0.94      0.96      1439
          weighted avg       0.98      0.98      0.98      1439



In [17]:
print(confusion_matrix(y_test, y_pred))

[[142   0   1   1   1   1   0   0   0   0]
 [  0 693   0   0   0   1   0   0   0   0]
 [  0   0 105   1   0   0   0   0   0   0]
 [  2   3   0  52   0   0   0   0   0   0]
 [  1   0   0   0  89   0   0   0   0   0]
 [  0   0   0   0   2 229   0   0   0   0]
 [  0   0   0   0   0   0  54   0   0   0]
 [  2   0   0   0   3   1   0  14   0   0]
 [  0   0   0   0   0   0   2   0  15   0]
 [  1   0   0   0   0   0   0   0   0  23]]
