CPC251 PROJECT PART 2
*   AZRI ZAMRUD BIN KIMIN ( 153507 )
*   HAZIQ BIN HIZUL ( 152770 )
*   MUHAMMAD ARMAND BIN MUHAMAD FAZLI ( 153857 )
*   SYED MUHAMMAD HAIKAL BIN SYED HUSNI ( 153086 ) 

In [24]:
import io
df2 = pd.read_csv(io.BytesIO(df['frogs_mfcc.csv']))
# Dataset is now stored in a Pandas Dataframe

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [22]:
#import standard libraries
import pandas as pd
import numpy as np
import tensorflow as tf
%config Completer.use_jedi = False

#import sklearn libraries
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import LassoCV
from sklearn.datasets import make_circles
from sklearn.svm import SVC
from sklearn import preprocessing
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from collections import OrderedDict
from numpy import loadtxt

#import keras model libraries
from keras.models import Sequential
from keras.layers import Dense
import warnings
warnings.filterwarnings('ignore')

In [23]:
#import the frog_mfcc csv dataset here after run this section
from google.colab import files
df = files.upload()

Saving frogs_mfcc.csv to frogs_mfcc (1).csv


In [25]:
df2.columns = range(df2.shape[1])   # Delete headers
X = df2.drop([22], axis=1).values 

y = df2[22]
y = y.values

print(X.shape)
print(y.shape)

(7195, 22)
(7195,)


In [27]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
loss_fn= tf.keras.losses.SparseCategoricalCrossentropy()
from sklearn.preprocessing import LabelEncoder
lb= LabelEncoder()
y = lb.fit_transform(y)
X = scaler.fit_transform(X)

In [28]:
from sklearn.model_selection import train_test_split
seed_num = 0
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=seed_num)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.1, random_state=seed_num)
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(5180, 22)
(576, 22)
(1439, 22)


In [29]:
from tensorflow.keras.models import Sequential
model = tf.keras.models.Sequential([
tf.keras.layers.Input(shape=(22,)),
tf.keras.layers.Dense(50, activation='relu', dtype='float64'),
tf.keras.layers.Dense(1, activation='sigmoid', dtype='float64')
])

In [30]:
predictions = model(X_train[:1]).numpy()
predictions

array([[0.50761144]])

In [31]:
loss_fn = tf.keras.losses.BinaryCrossentropy()

In [32]:
loss_fn(y_train[:1], predictions).numpy()

0.647590696811676

In [33]:
model.compile(optimizer = 'adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [34]:
model.fit(X_train, y_train, batch_size=64, epochs=10)

Epoch 1/10
81/81 [==============================] - 1s 2ms/step - loss: -3.3465 - accuracy: 0.4846
Epoch 2/10
81/81 [==============================] - 0s 2ms/step - loss: -15.0955 - accuracy: 0.4849
Epoch 3/10
81/81 [==============================] - 0s 1ms/step - loss: -38.1608 - accuracy: 0.4849
Epoch 4/10
81/81 [==============================] - 0s 2ms/step - loss: -73.8262 - accuracy: 0.4849
Epoch 5/10
81/81 [==============================] - 0s 1ms/step - loss: -121.6660 - accuracy: 0.4849
Epoch 6/10
81/81 [==============================] - 0s 2ms/step - loss: -180.9320 - accuracy: 0.4849
Epoch 7/10
81/81 [==============================] - 0s 2ms/step - loss: -251.9471 - accuracy: 0.4849
Epoch 8/10
81/81 [==============================] - 0s 1ms/step - loss: -337.3638 - accuracy: 0.4849
Epoch 9/10
81/81 [==============================] - 0s 2ms/step - loss: -437.0558 - accuracy: 0.4849
Epoch 10/10
81/81 [==============================] - 0s 2ms/step - loss: -549.1242 - accuracy: 0

In [35]:
model.evaluate(X_test, y_test, verbose=1)

45/45 [==============================] - 0s 1ms/step - loss: -612.4713 - accuracy: 0.4837


[-612.4713134765625, 0.4836692214012146]

In [36]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
y_pred = model.predict(X_test)
y_pred = np.round(y_pred) # round the predicted value y >= 0.5 is 1 else 0
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.4836692147324531
[[  0 139   0   0   0   0   0   0   0   0]
 [  0 696   0   0   0   0   0   0   0   0]
 [  0  95   0   0   0   0   0   0   0   0]
 [  0  68   0   0   0   0   0   0   0   0]
 [  0  98   0   0   0   0   0   0   0   0]
 [  0 226   0   0   0   0   0   0   0   0]
 [  0  53   0   0   0   0   0   0   0   0]
 [  0  20   0   0   0   0   0   0   0   0]
 [  0  13   0   0   0   0   0   0   0   0]
 [  0  31   0   0   0   0   0   0   0   0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       139
           1       0.48      1.00      0.65       696
           2       0.00      0.00      0.00        95
           3       0.00      0.00      0.00        68
           4       0.00      0.00      0.00        98
           5       0.00      0.00      0.00       226
           6       0.00      0.00      0.00        53
           7       0.00      0.00      0.00        20
           8       0.00      0.00      0.00        13
         

In [37]:
#confusion matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix\n\n', cm)

Confusion matrix

 [[  0 139   0   0   0   0   0   0   0   0]
 [  0 696   0   0   0   0   0   0   0   0]
 [  0  95   0   0   0   0   0   0   0   0]
 [  0  68   0   0   0   0   0   0   0   0]
 [  0  98   0   0   0   0   0   0   0   0]
 [  0 226   0   0   0   0   0   0   0   0]
 [  0  53   0   0   0   0   0   0   0   0]
 [  0  20   0   0   0   0   0   0   0   0]
 [  0  13   0   0   0   0   0   0   0   0]
 [  0  31   0   0   0   0   0   0   0   0]]


In [45]:
svc = SVC(kernel='linear', C=10.0, random_state=1)
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)

#classification report
print("\n")
print(classification_report(y_test, y_pred))

#confusion matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix\n\n', cm)

Analysis for Neural Network:
------------------------------------


              precision    recall  f1-score   support

           0       0.95      0.93      0.94       139
           1       1.00      1.00      1.00       696
           2       0.91      0.99      0.95        95
           3       0.95      0.87      0.91        68
           4       0.92      1.00      0.96        98
           5       0.99      0.97      0.98       226
           6       0.98      0.96      0.97        53
           7       0.81      0.65      0.72        20
           8       0.93      1.00      0.96        13
           9       1.00      0.97      0.98        31

    accuracy                           0.97      1439
   macro avg       0.94      0.93      0.94      1439
weighted avg       0.98      0.97      0.97      1439

Confusion matrix

 [[129   0   7   1   0   1   0   0   1   0]
 [  0 696   0   0   0   0   0   0   0   0]
 [  0   0  94   1   0   0   0   0   0   0]
 [  6   1   2  59   0   0